### ISSUE TITLE
Problem with parsing bindings.xjb

### ISSUE THREAD

**Issue by mathewstars** [davidmoten/xjc-maven-plugin#1]
When I try to use bindings.xjb file (was working before and its working if I use XJBFacade alone), even though XJB file is processes (compilation fails if path is incorrect), there are still warnings.
I tried to replace plugin xjb dependencies with 2.3.2 (instead of beta 2.4) but with no luck.

[WARNING] Simple type "field-level4" was not mapped to Enum due to EnumMemberSizeCap limit. Facets count: 389, current limit: 256. You can use customization attribute "typesafeEnumMaxMembers" to extend the limit.
  line 828 of file:/Users/mathew/Workspaces/sigp-apps/ejb/src/main/resources/schemas/europass/EuropassISCO_88_COM_V1.4.0.xsd

xjb content:
<bindings
        xmlns="http://java.sun.com/xml/ns/jaxb"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        version="2.1">

	<bindings>
		<globalBindings underscoreBinding="asCharInWord" typesafeEnumMaxMembers="9000" typesafeEnumMemberName="generateName"/>
	</bindings>
</bindings>

**Comment by davidmoten** [comment]
Thanks @mathewstars. Seems to be a problem with *jaxb-xjc* and it's happening to me too. I've got some simple binding tests that pass and more complicated ones (kml 2.2 schema) where I see the same behaviour as you. The bindings are parsed but then ignored. This will be a bug with *jaxb-xjc* I think and I'll continue trying to isolate it so I can raise the problem with Eclipse foundation and perhaps come up with a workaround or patch to put in the plugin. I tried a number of versions of *jaxb-xjc* and all had the same behaviour. Let me know if you make any progress isolating it.

**Comment by mathewstars** [comment]
you know what is strange? like this it works even with jaxb 2.4 beta (this however terminates maven process violently with exit code 0)
when I comment out -b argument its same as with your plugin, with it active binding is processed well

	        <plugin>
		        <groupId>org.codehaus.mojo</groupId>
		        <artifactId>exec-maven-plugin</artifactId>
		        <version>1.6.0</version>
		        <executions>
			        <execution>
				        <phase>generate-sources</phase>
				        <goals>
					        <goal>java</goal>
				        </goals>
				        <configuration>
					        <includePluginDependencies>true</includePluginDependencies>
					        <mainClass>com.sun.tools.xjc.XJCFacade</mainClass>
					        <arguments>
						        <argument>-extension</argument>
						        <argument>-encoding</argument>
						        <argument>UTF-8</argument>
						        <argument>-d</argument>
						        <argument>${jaxb.output.dir}</argument>
						        <argument>-b</argument>
						        <argument>ejb/src/main/resources/xjb/bindings.xjb</argument>
						        <argument>ejb/src/main/resources/schemas/europass/EuropassSchema.xsd</argument>
					        </arguments>
				        </configuration>
			        </execution>
		        </executions>
		        <dependencies>
			        <dependency>
				        <groupId>org.glassfish.jaxb</groupId>
				        <artifactId>jaxb-xjc</artifactId>
				        <version>2.4.0-b180830.0438</version>
			        </dependency>
		        </dependencies>
	        </plugin>

**Comment by davidmoten** [comment]
@mathewstars that is interesting. Perhaps one of the other dependencies against the plugin is busting things. I guess plexus-classworlds is an obvious candidate to check given the discussion on jaxb2-maven-plugin.

**Comment by davidmoten** [comment]
Tried upgrading with plexus-classworlds 2.6.0 but start getting other errors due to incompatibility. Given that the method you are talking about works I might go down that path (fork a process, setting the classpath). At least we end up with a tightly controlled classpath and I'll be able to avoid the System.exit called by that method. I'll give that a shot in an hour or two.

**Comment by davidmoten** [comment]
I went down the rabbit hole that forked a process etc and got the same results with the kml 2.2 schema. Turns out I was being bitten by https://github.com/eclipse-ee4j/jaxb-ri/issues/1073. When I removed the offending attribute on globalBindings `optionalProperty="primitive"` then started working (haven't evaluated the consequence of that attribute not being there yet!).

**Comment by davidmoten** [comment]
~~So my problem is addressed, can you submit your schemas and bindings files so I've got a test case?~~

**Comment by davidmoten** [comment]
might have jumped the gun, not sure the kml 2.2 case is fixed...

**Comment by davidmoten** [comment]
Ah good, I do need to call a new process with a restricted classpath for it all to work. I've added the kml test  to *xjc-maven-plugin-test* to pick this up. @mathewstars can you try your case with master now?

**Comment by davidmoten** [comment]
0.1.2 has been released that should fix this problem. Please try it out.

**Comment by mathewstars** [comment]
amazing work @davidmoten it does work well 0.1.2 

although there is still some kind of strange output it maven console
[INFO] generating code
unknown location

does it mean something or should I ignore it?

**Comment by davidmoten** [comment]
Great, I'm glad it works for you. The `unknown location` message is produced by `xjc` every time for me. Doesn't seem to matter, but you're welcome to research it if you want to. I might have a look this weekend. I think it's ignorable because if it wasn't `xjc` would fail (and the maven build would fail).

**Comment by davidmoten** [comment]
Ok I've looked into it. The `unknown location` bit is associated with the `generating code` log line and corresponds to this call in `XJCBase.ErrorReceiverImpl`:

```java
private void print(int logLevel, String header, SAXParseException e) {
    log(Messages.format(header, e.getMessage()), logLevel);
    log(getLocationString(e), logLevel);
    log("", logLevel);
}
```

`getLocationString(e)` returns `unknown location` in this instance and is ignorable (though would be nice if XJC didn't print that for a simple log line).

**Comment by davidmoten** [comment]
I'll close this now, reopen it if you have any more concerns.

**Comment by mathewstars** [comment]
Thank you
